path: C:/Users/10000/Desktop/Finished/Index/cvat
train: images/train
val: images/train
names:
  0: ADONIS
  1: AFRICAN GIANT SWALLOWTAIL
  3: AMERICAN SNOOT
  4: AN 88
  5: APPOLLO
  6: ARCIGERA FLOWER MOTH
  7: ATALA
  8: ATLAS MOTH
  9: BANDED ORANGE HELICONIAN
  10: BANDED PEACOCK
  11: BANDED TIGER MOTH
  12: BECKERS WHITE
  13: BIRD CHERRY ERMINE MOTH
  14: BLACK HAIRSTREAK
  15: ADONIS9
  16: ADONIS10
  17: ADONIS
  18: ADONIS
  19: ADONIS
  20: ADONIS
  21: ADONIS
  22: ADONIS
  23: ADONIS
  24: ADONIS
  25: ADONIS
  26: ADONIS
  27: ADONIS
  28: ADONIS
  29: ADONIS
  30: ADONIS
  31: ADONIS
  32: ADONIS
  33: ADONIS
  34: ADONIS
  35: ADONIS
  36: ADONIS
  37: ADONIS
  38: ADONIS
  39: ADONIS
  40: ADONIS
  41: ADONIS
  42: ADONIS
  43: ADONIS
  44: ADONIS
  45: ADONIS
  46: ADONIS
  47: ADONIS
  48: ADONIS
  49: ADONIS
  50: ADONIS
  51: ADONIS
  52: ADONIS
  53: ADONIS
  54: ADONIS
  55: ADONIS
  56: ADONIS
  57: ADONIS
  58: ADONIS
  59: ADONIS
  60: ADONIS
  61: ADONIS
  62: ADONIS
  63: ADONIS
  64: ADONIS
  65: ADONIS
  66: ADONIS
  67: ADONIS
  68: ADONIS
  69: ADONIS
  70: ADONIS
  71: ADONIS
  72: ADONIS
  73: ADONIS
  74: ADONIS
  75: ADONIS
  76: ADONIS
  77: ADONIS
  78: ADONIS
  79: ADONIS
  80: ADONIS
  81: ADONIS
  82: ADONIS
  83: ADONIS
  84: ADONIS
  85: ADONIS
  86: ADONIS
  87: SILVER SPOT SKIPPER
  88: SIXSPOT BURNET MOTH
  89: SLEEPY ORANGE
  90: SOOTYWING
  91: STRAITED QUEEN
  92: TROPICAL LEAFWING
  93: TWO BARRED FLASHER
  94: ULYSES
  95: VICEROY
  96: WHITE LINED SPHINX MOTH
  97: WOOD SATYR
  98: YELLOW SWALLOW TAIL
  99: ZEBRA LONG WING
